#pragma once

enum class COMMANDS {
  WRITE = 1,
  COLOR = 2,
};

enum class COLORS {
  BLACK,
  BLUE = FOREGROUND_BLUE,
  GREEN = FOREGROUND_GREEN,
  AQUA = FOREGROUND_GREEN | FOREGROUND_BLUE,
  RED = FOREGROUND_RED,
  PURPLE = FOREGROUND_BLUE | FOREGROUND_RED,
  YELLOW = FOREGROUND_GREEN | FOREGROUND_RED,
  WHITE = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_RED,
  GRAY = FOREGROUND_INTENSITY,
  LIGHT_BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
  LIGHT_GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
  LIGHT_AQUA = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
  LIGHT_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
  LIGHT_PURPLE = FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY,
  LIGHT_YELLOW = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY,
  BRIGHT_WHITE = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY,
};